### ISSUE TITLE
mintMenu not setting SSH_AUTH_SOCK properly

### ISSUE THREAD

**Issue by cbhushan** [linuxmint/mintmenu#107]
More details and discussions on following links: 

http://forums.linuxmint.com/viewtopic.php?t=172522
http://forums.mate-desktop.org/viewtopic.php?t=3146

**Comment by xenopeek** [comment]
This doesn't affect Linux Mint 18.3 so I assume it was fixed (in some component) since this issue was investigated. Closing.
