### ISSUE TITLE
Alphabetical order for accentuated characters

### ISSUE THREAD

**Issue by donlencho** [linuxmint/mintmenu#113]
In French, program names starting with an accentuated character, "Éditeur de texte" for instance, are listed at the end of the list, after Z. The alphabetical order should ignore accents, putting "Éditeur de texte" with the E.

**Comment by donlencho** [comment]
Still the same in Nemo, but corrected in MintMenu with 17.1

**Comment by xenopeek** [comment]
Seeing as the original issue was already reported as fixed, and other mentioned observations have also been fixed (Nemo sorts ÉAA before EEE for example, not after) closing this.
