### ISSUE TITLE
feature request : add icons in recent documents list

### ISSUE THREAD

**Issue by denispr** [linuxmint/mintmenu#116]
The title is self explaining, it would be more user friendly if mimetype icons were displayed in recent documents list.

**Comment by monsta** [comment]
Would be nice. But then I'd also make the list entries aligned to the left - it would look better with icons that way, I think.

**Comment by denispr** [comment]
I agree that left alignment would look better.
Also, I just installed LMDE 2 RC, and noticed that now recent files have icons, great !
Just one thing though : folders displayed in the recent documents list don't have icons.
