### ISSUE TITLE
Can not open Wine applications shortcuts via mintMenu

### ISSUE THREAD

**Issue by unxed** [linuxmint/mintmenu#122]
1. Install some app in Wine
2. Try to launch it via mint menu
3. "File not found" message appears

Mint Mate 17.1

**Comment by unxed** [comment]
Looks like the problem is that in non-english wine Desktop folder name can contain spaces.
For example, in russian it is named "Рабочий стол".
So all paths must be escaped with quotes in .desktop files.
Not sure if it is mintmenu bug or wine's one.

**Comment by xenopeek** [comment]
This would have been a Wine issue. The Exec entry in a .desktop file requires quoting or escaping of space in paths: https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables. Closing as this wasn't an issue solvable in mintmenu.
