### ISSUE TITLE
Remove from favorites with right click option 'remove'

### ISSUE THREAD

**Issue by hrvoojex** [linuxmint/mintmenu#128]
When you want to remove an item from favorites, you have to find it in a menu and then right click and select 'remove from favorites'.

Would it be possible to remove it right from the favorites menu with a right click or a mouse?

**Comment by monsta** [comment]
Implemented long ago and working fine.

P.S. In case you meant Cinnamon's panel menu, the bug report should be filed at https://github.com/linuxmint/Cinnamon/issues. This place is for MATE's panel menu.
