### ISSUE TITLE
short key to launch menu not properly recorded

### ISSUE THREAD

**Issue by denispr** [linuxmint/mintmenu#132]
In mintmenu preferences dialog, to set mintmenu short key to Control+Super, pressing Control first then Super key does not work : it records <Super>Control_L instead of <Control>Super. To record Control+Super, one has to press first Super then Control !
(mintmenu 5.6.0 on Linux Mint 17.1)

**Comment by philipzae** [comment]
So i tested mintMenu 5.6.6 on Linux Mint 17.3 and if you press Control+Super by quickly pressing Control and then Super, it shows up as <Super>Control_L. But if you hold Control atleast for 1 second before pressing Super, it shows up as <Primary>Super_L.

**Comment by denispr** [comment]
Yes, same here for me. Strange behaviour, but anyway, as soon as it lets me setting the right short key, everything is fine !

**Comment by xenopeek** [comment]
Retesting on Linux Mint 18.3 MATE, it records the shortcut in the order that you press the keys. If you hold down Ctrl and then press Super, it records <Primary>Super_L. If instead you hold down Super and then press Ctrl it records <Super>Control_L. If you try to press the keys at the same time it records either the one or the other, depending on which key you did press first.

To open the menu you have to press the keys in the same order. So if you recorded it by holding down Ctrl and then pressing Super, that's how you open the menu. If in that example you try to hold down Super and then press Ctrl, that's a different shortcut and the menu won't open.

This reads differently from the original issue though it may still be a bit confusing if you tried to press the keys at the same time. For now closing this issue.
