### ISSUE TITLE
Feature request - GTK+3 support for use with MATE-Compiz

### ISSUE THREAD

**Issue by arehtykitna** [linuxmint/mintmenu#133]
Hello, I really like using mintmenu in Fedora MATE-Compiz. A throw-back from previously running Mint Isadora on my notebook. I still haven't found a better menu system for MATE.

Currently there is a GTK+3 version of Fedora MATE-Compiz being developed (which I am testing in VM) and I would love to be able to carry on using mintmenu with that eventually.

Right now, mintmenu isn't compatible and just crashes if you try and add it to the GTK+3 panel.

So is there any chance you will be able to create a GTK+3 compatible version?

**Comment by clefebvre** [comment]
Hi,

Yes. We're hoping to switch MATE to GTK3 in version 1.16 and part of that, for us, will be to port mintmenu to GTK3.

I'm closing this issue in the meantime.

**Comment by arehtykitna** [comment]
Thanks Clem, I look forward to the official GTK+3 release. I've been
using development builds of GTK+3 MATE in Fedora for a couple of
releases.

**Comment by clefebvre** [comment]
Update: it should happen with MATE 1.18 now and Mint 18.2, hopefully.

**Comment by arehtykitna** [comment]
Thanks for the update. @raveit65 has kindly ported the Advanced Mate Menu from UbuntuMATE for Fedora 25. It works okay but I miss the ability to drag and drop favourite list entries to reorder them from the GTK2 mintmenu. A very minor thing in the general scheme of things though ;)

**Comment by monsta** [comment]
Update: #162 is merged into master branch, the remaining issues will be addressed later.
