### ISSUE TITLE
mintmenu not working with python 2.7.10

### ISSUE THREAD

**Issue by catalin-hritcu** [linuxmint/mintmenu#134]
mintmenu is broken on Arch Linux for almost a month, since the 2.7.10 upgrade to Python. More details here: https://aur.archlinux.org/packages/mintmenu/?comments=all

**Comment by GLolol** [comment]
This is certainly not an issue with a Python 2.7.x upgrade; Arch's default `python` uses Python 3! #135 should be an adequate fix.

**Comment by catalin-hritcu** [comment]
Arch's default python uses Python 3 since forever. I don't think this is a recent change lie the 2.7.10 upgrade.

**Comment by GLolol** [comment]
The AUR comments seem to be a mix of different issues all plastered into one section. But, the comment from josealb77 suggests that the shebang is wrong - only Python 3 would complain about print missing parenthesis; it is valid in Python 2.
```
[josealb77@ArchLinux ~]$ mintmenu
File "/usr/bin/mintmenu", line 7
print "mintMenu - the advanced MATE menu\n"
^
SyntaxError: Missing parentheses in call to 'print'
[josealb77@ArchLinux ~]$ 
```

**Comment by catalin-hritcu** [comment]
Sorry for the confusion, but I have no clue why he was getting this and I don't know if it's related to the issue. All I get in the console is this:
```
[hritcu@detained pub]$ python2 --version
Python 2.7.10
[hritcu@detained pub]$ mintmenu         
/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
[hritcu@detained pub]$
```
and this warning is appearing even after downgrading to 2.7.9:
```
[hritcu@detained pub]$ python2 --version
Python 2.7.9
[hritcu@detained pub]$ mintmenu         
/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
```
I'll try a reboot to see if that helps get a better error message.

**Comment by catalin-hritcu** [comment]
All I managed to get after the restart with python 2.7.10 was a graphical error message that looks like this: "mintMenu has quit unexpectedly"
![screenshot from 2015-06-26 10-07-12](https://cloud.githubusercontent.com/assets/5850655/8372341/c52d6c70-1be2-11e5-85c0-cd864c5ccf8d.png)
Hitting the "reload" button causes the same error to appear, and hitting "don't reload" makes it go away.

Running mintmenu in the terminal causes the same warning, then no output:
```
[hritcu@detained ~]$ mintmenu
/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)

```
and this time no return to the terminal other than with killall mintmenu.

Please let me know if there is anything more I can do to diagnose this better.

**Comment by catalin-hritcu** [comment]
Can anyone please reopen this one, it's not yet fixed.

**Comment by GLolol** [comment]
That's looks more like a warning, not an error which would cause the app to crash. 

Possibly related? https://bugs.launchpad.net/linuxmint/+bug/1261862

**Comment by catalin-hritcu** [comment]
Not sure if it's the same problem, but indeed I also get a segfault in dmesg:
```
[   55.856017] mintmenu[1686]: segfault at ffffffff8a6d5830 ip 00007f3987b993e5 sp 00007ffc68347b88 error 5 in libgobject-2.0.so.0.4400.1[7f3987b66000+4f000]
```

**Comment by GLolol** [comment]
That seems to be a different issue completely, and something with libgobject/python-gobject I'm not entirely sure of.

**Comment by catalin-hritcu** [comment]
I'm not sure what you mean by "different issue completely" (different than what?), but the sefgault doesn't seem different from this: https://bugs.launchpad.net/linuxmint/+bug/1261862/comments/7

**Comment by GLolol** [comment]
I meant it was different from the RuntimeWarning and the "print without parenthesis" issues.

**Comment by catalin-hritcu** [comment]
Indeed, any chance for reopening this issue and making it about the segfault?

**Comment by GLolol** [comment]
I'd open a new issue just to reduce confusion.
