### ISSUE TITLE
Higher RAM usage on pure Debian (not LMDE)

### ISSUE THREAD

**Issue by moihack** [linuxmint/mintmenu#138]
![lmde-live](https://cloud.githubusercontent.com/assets/2737980/8442186/f6ee7cb2-1f85-11e5-9480-9f48c53a1b7d.png)
![menu-idle](https://cloud.githubusercontent.com/assets/2737980/8442187/f6ef075e-1f85-11e5-86d8-675a9807277a.png)
![menu-opened](https://cloud.githubusercontent.com/assets/2737980/8442188/f6f22c36-1f85-11e5-8626-40c812554724.png)

Hello.
I've installed mintmenu manually on my Debian Jessie (32bit)MATE system using the .deb file you provide here: http://packages.linuxmint.com/list.php?release=Betsy.
The menu works really well(no lag or something that hurts the user experience).
However I noticed somewhat high ram usage (almost 70mb) which seems a little too high for what the menu does.
But the strange thing is that the menu runs on much lower ram when it hasn't been opened for the current session.

I then decided to give LMDE Betsy MATE (32bit) edition a try to see if this happens on the platform it was designed to run. As you can guess from the screenshots it isn't happening (although the different task managers show different ram values - but either way none of them shows 70mb like my Debian MATE system).

I tried installing an older version  of mintmenu(5.5.1) as well as upgrade to testing my Debian system (the screenshots are from testing - ram usage was same on stable) but the "problem" still persists.

I also installed mate-menu on my now Debian testing system from the debian repositories but its ram usage was exactly like mintmenu(low when never opened for the current session and as soon as I opened it, it bumped to about 70mb).
I can provide screenshots for this as well.
Unfortunately I din't try mate-menu on live LMDE since it isn't on the stable repository.

I know mintmenu was designed with Linux Mint in mind but are LMDE and Debian really that much different to justify the increase in ram usage for mintmenu?
I will probably continue using mintmenu despite the increased ram usage (I have 4gb of ram as seen on the screenshots) but I think a fix for this issue would really help computers with much less ram (about 1gb or so) enjoy your great piece of software without wasting too much system resources.

Cheers!

**Comment by xenopeek** [comment]
Given the age of this issue and that we're on mintmenu 5.8.4 currently (instead of 5.5.1 at time of this issue), I'm closing it.

If the issue happens again, please test against the latest mintmenu version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintmenu.
