### ISSUE TITLE
mintmenu does not start anymore in fedora 23

### ISSUE THREAD

**Issue by raveit65** [linuxmint/mintmenu#141]
Origin report with full stacktrace at https://bugzilla.redhat.com/show_bug.cgi?id=1278753

mintmenu: g_type_check_instance_is_fundamentally_a(): python2.7 killed by SIGSEGV
```
Truncated backtrace:
Thread no. 1 (10 frames)
 #0 g_type_check_instance_is_fundamentally_a at gtype.c:4030
 #1 g_object_get_qdata at gobject.c:3235
 #2 pygobject_new_full at pygobject.c:969
 #3 ffi_call_unix64 at ../src/x86/unix64.S:76
 #4 ffi_call at ../src/x86/ffi64.c:525
 #5 _call_function_pointer at /usr/src/debug/Python-2.7.10/Modules/_ctypes/callproc.c:836
 #6 _ctypes_callproc at /usr/src/debug/Python-2.7.10/Modules/_ctypes/callproc.c:1179
 #7 PyCFuncPtr_call at /usr/src/debug/Python-2.7.10/Modules/_ctypes/_ctypes.c:3965
 #8 PyObject_Call at /usr/src/debug/Python-2.7.10/Objects/abstract.c:2529
 #9 do_call at /usr/src/debug/Python-2.7.10/Python/ceval.c:4330
```
Starting mintmenu from a terminal shows me a new warning
```
  warnings.warn(warn_msg, RuntimeWarning)
/usr/share/linuxmint/mintMenu/mintMenu.py:7: PyGIWarning: MatePanelApplet was imported without specifying a version first. Use gi.require_version('MatePanelApplet', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import MatePanelApplet
```
But adding gi.require_version('MatePanelApplet', '4.0') to /mintMenu.py kills the warning, but mintmenu doesn't start.
Also i tried to disable all plugins, but no luck.
gsettings get com.linuxmint.mintmenu plugins-list
['places', 'system_management', 'newpane', 'applications']

Note, mintmenu in fedora 22 runs well.
For testing you can download a f23 livecd at https://spins.fedoraproject.org/en/mate-compiz/

**Comment by monsta** [comment]
Stacktrace looks suspiciously similar to the one in https://github.com/linuxmint/mintmenu/issues/137...

**Comment by raveit65** [comment]
thanks  for the tip, updating to 5.6.5 solves the issue :)
