### ISSUE TITLE
Mint menu has title bar "MintMenu.py"

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintmenu#147]
After upgrading to 17.3, the mintmenu has changed and now has a title bar called "MintMenu.py" when i use the clearlooks theme. This didnt happen in 17.2.

![mintmenu clearlooks](https://cloud.githubusercontent.com/assets/4412114/11952408/6d9e2a9c-a8b1-11e5-8559-65d4030bb3f9.png)

**Comment by monsta** [comment]
Fixed in 5.6.6
