### ISSUE TITLE
Mate menu searches files when pressing enter instead of launching the application - can this be changed?

### ISSUE THREAD

**Issue by cipricus** [linuxmint/mintmenu#149]
Example: I press Supper button: menu opens. I write "fir" in order to launch Firefox: it shows Firefox, just like any launcher. I press Enter, it starts searching the whole system for files named "fir".

I can avoid this by pressing down-arrow before Enter but I find this behavior odd and want to change it, because launching an application is needed much more often than searching the whole system for a file. 

The Application search-selection-launch should be the first option instead of the file-search.

**Comment by RobLoach** [comment]
Agreed... Hitting *ENTER* should launch the top-most application in the list.

Saw @blc56 started some work on this over at:
https://github.com/blc56/mintmenu/tree/blc_enter

**Comment by dd23** [comment]
His changes (the last two commits [here](https://github.com/blc56/mintmenu/commits/blc_enter)) work fine. I just tested this on Mint 17.3 with Mate 1.12 and MintMenu 5.6.6.  
Ideally, it should be made configurable, though.

**Comment by motevets** [comment]
:+1: I [rebased @blc56 's branch with master](https://github.com/motevets/mintmenu/tree/feature-enter_execute_match), without incident.  I'd be happy to work on making this configurable if @clefebvre is open to a PR with this feature.

**Comment by dd23** [comment]
Great, thanks! 
One minor remark: I'm not sure, but you probably don't want to include this `install` and `test` file.

**Comment by MichaelTunnell** [comment]
I'd also suggest taking a look at the code in MATE Menu which is a fork of the mintmenu used in Ubuntu MATE, they fixed this issue as well.

**Comment by RobLoach** [comment]
Martin Wimpress [committed this changelog to "Launch highlighted appliction with Enter key"](https://bitbucket.org/ubuntu-mate/mate-menu/commits/19fa0566faa7029252204b7d5baa8860af594fbf) in Ubuntu Mate Menu, which is a fork of Mint Menu. While it's not an option, it is functional.

**Comment by dd23** [comment]
@RobLoach The [Ubuntu mate commit you refer to](https://bitbucket.org/ubuntu-mate/mate-menu/commits/19fa0566faa7029252204b7d5baa8860af594fbf) is the same one as [blc56's](https://github.com/blc56/mintmenu/commit/d384a6278cda0f90e142bfad28ac7e4444cbd04e) [commits](https://github.com/blc56/mintmenu/commit/0424cf5e104aacc875e4077cd0619f2b04699a03), that @motevets [already included into mintmenu](https://github.com/motevets/mintmenu/commit/ebf0e5f676a5d3ae447e4007791e7fd9d6daecea) as mentioned above (minus some spacing and said `test` and `install` file).

**Comment by clefebvre** [comment]
Hi @motevets, everybody.

I agree, this is annoying and pressing Enter should launch the top app in the list. I'll add that to the roadmap now and if somebody can create a PR for this, I'll be happy to merge it.

PS: I don't really see the need for this to be configurable.

**Comment by motevets** [comment]
@clefebvre please see PR #151 above, thanks!

**Comment by clefebvre** [comment]
Thanks :)

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintmenu/commit/e12dee7b017b1c187296b2d8e4080c85086563d0
