### ISSUE TITLE
auto highlight first entry when searching

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintmenu#150]
It would be great if when searching the first entry in the results was auto highlighted so you dont have to press down to highlight it before pressing enter. This feature is in cinnamon's application launcher.

**Comment by UnoSD** [comment]
I totally agree; in addition it gives a consistent behaviour between Windows and Linux making it easy for user to switch between the two. Please consider implementing this feature.

**Comment by motevets** [comment]
Hey guys, we're talking about this over in #149.

**Comment by clefebvre** [comment]
This was implemented already.
