### ISSUE TITLE
Desktop files are missing in mintMenu using Flatpak apps

### ISSUE THREAD

**Issue by diazbastian** [linuxmint/mintmenu#153]
### System:

Fedora 24 Workstation
MATE Desktop 1.14.1
mintMenu 5.6.5
I tested with Linux Mint vs Arch Linux on a virtual machine with the same results.
### Issue:

When installing the Flatpak format applications, these applications are not displayed the in mintMenu, unlike other menu-Mate applets, or other instance of the system (eg. "opened with..." dialogue). Can become annoying creating custom launchers for mintMenu (duplicated in other instances).

![bug](https://cloud.githubusercontent.com/assets/5126124/16467032/cb0dec94-3e1b-11e6-8790-4187b6f6269b.png)

**Comment by mtwebster** [comment]
Is `/var/lib/flatpak/exports/share` in your `XDG_DATA_DIRS` environment variable?  I'm running into an issue on mint, but in my case, they're not showing anywhere.  Looking at mintmenu briefly, it should be picking it up if that is set.

**Comment by diazbastian** [comment]
Yeah, I tested with the default settings and then adding the specific variable, but only in mintMenu not work. I have also some Flatpak applications installed in my local user and is the same.

**Comment by xenopeek** [comment]
This doesn't appear to affect current version of mintmenu.

If the issue happens again, please test against the latest mintmenu version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintmenu.
