### ISSUE TITLE
Setting "selected items" background in "appearance" messes up with font colour in mintmenu

### ISSUE THREAD

**Issue by dlussky** [linuxmint/mintmenu#158]
Steps to reproduce:
1. Set the main theme to Mint-Y-Darker
2. Set menu theme to Mint-Y-Dark ("use custom colours" stays disabled). At this point everything is looking great, but I don't personally like green.
3. Open "Customize" in "Appearance preferences" and change "Selected items" background

What am I expecting:
Menu should stay the same

What happens:
Menu becomes unreadable (text colour becomes dark).

Video demonstration: https://youtu.be/yG4baU_wKYM

**Comment by xenopeek** [comment]
Retesting on Linux Mint 18.3 MATE I don't find an the option to change "Selected items". It appears MATE has changed and doesn't allow for this fine-grained customization of themes.
