### ISSUE TITLE
missing tags

### ISSUE THREAD

**Issue by glensc** [linuxmint/mintmenu#159]
https://github.com/linuxmint/mintmenu/tags
last tag 5.5.2...

please tag the releases. even you don't upload tarballs to github it's useful to have releases tagged

**Comment by clefebvre** [comment]
Will do. We tag cross-distro projects, but not our own tools. That being said mintMenu is being used outside of Mint, so your request is making a lot of sense.

Please let me know if you need a particular tag. I'll apply one for the latest version anyhow.

**Comment by glensc** [comment]
if the problem is that tags don't even exist, not that they aren't pushed to github,

then perhaps just start tagging from now on and push the tags.
this way projects like https://release-monitoring.org/ can monitor the new release
and i as external distribution linux maintainer can update my distro with the new release.

**Comment by clefebvre** [comment]
No problem. We'll tag mintmenu releases from now on.
