### ISSUE TITLE
Ignores .desktop files in $XDG_DATA_HOME/share/applications

### ISSUE THREAD

**Issue by probonopd** [linuxmint/mintmenu#164]
When I put .desktop files in `$XDG_DATA_HOME/share/applications` then they are ignored by (= not shown in) the menu. Where am I supposed to put .desktop files for a per-user installation?

This is on `linuxmint-17.3-cinnamon-64bit.iso`.

**Comment by Magissia** [comment]
per user share is hidden, "$XDG_DATA_HOME/share" is not valid.
You're supposed to use "~/.local/share/applications".
$XDG_DATA_HOME doesn't even seem to be set by default.

**Comment by probonopd** [comment]
According to https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html, $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. _If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used._

Currently I am using the [`g_get_user_data_dir()`](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-user-data-dir) function from glib to determine the directory like this:
```
dest_dir = g_build_path("/", g_get_user_data_dir(), "/icons/hicolor/scalable/apps/", NULL);
```

**Comment by xenopeek** [comment]
As the issue was about Cinnamon's menu applet while mintmenu (this project) is for MATE, closing this. AFAIK ~/.local/share/applications works for current versions of Cinnamon, if it was indeed a problem before.
