### ISSUE TITLE
First run Mint Menu for Mate is very slow

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintmenu#168]
Hi
On my laptop, amd a4-5000 apu + ssd and obviously slower computers and laptops, when I opend menu first time, It open slower than normally, It is lagging. Can you loading menu data when system is starting or something else. Slow menu to affect very bad on user experience.

**Comment by Magissia** [comment]
On slower computer it can take full 15 second to open.

**Comment by xenopeek** [comment]
Is this issue still affecting users on Linux Mint 18.3 MATE? I see various changes to mintmenu since this issue was reporting that could have improved it's first run speed.

**Comment by xenopeek** [comment]
Actually, same issue as described in #56 so closing.
