### ISSUE TITLE
Laptop can't sleep after upgrade to kernel 4.4.0-67

### ISSUE THREAD

**Issue by ip413** [linuxmint/mintmenu#169]
Sleep don't work after upgrade to kernel 4.4.0-67 from 4.4.0-21. 
In 4.4.0-21 everything works fine.

When I hit Fn + Sleep (F4) button I see screen blinks two times and laptop is working as before.
After closing lid "sleep light" don't flash, and after opening it system already is working - don't "waking up".

Linux Mint, Mate, kernel 4.4.0-67. Thinkpad T430s.

**Comment by leigh123linux** [comment]
File your issue against the faulty kernel

**Comment by ip413** [comment]
Can you tell me where? I can't find proper place in web for this.
