### ISSUE TITLE
Possible Incorrect Icons 

### ISSUE THREAD

**Issue by callagg2** [linuxmint/mintmenu#175]
inxi -F
System:    Host: Aspire-R3700 Kernel: 4.4.0-53-generic x86_64 (64 bit)
Desktop: Cinnamon 3.4.0  Distro: Linux Mint 18.1 Serena

The icon for GParted 0.25.0 (Gnome Partition Editor) on my mintmenu differs greatly to that at http://gparted.org. The current icon looks similar to Baobab 3.18.1 (A graphical tool to analyze disk usage)

//Aside
The title bar of Baobab appears and behaves very different to other Mint programs. Firstly while other programs have a black title bar, this has a grey one. Upon opening, instead of saying the name "Disk Usage Analyzer", it says "Devices and locations" in the titlebar. This is not what you'd expect as it differs to how the titlebar works in nemo, notwithstanding that "locations" is spelt with a lowercase "l" in "Devices and locations" which just looks wrong.
I also don't agree with the positioning of the arrows on the right - to give you further breakdown on your hard drive, or your Home folder. This is then followed by a backward arrow hidden in the title bar. I think the whole structure should feel more consistent with Nemo. In Nemo, things are done right, you have a rightward pointing arrow to the left of say Home to elaborate. Clicking the rightward arrow, changes the arrow to a downward arrow, and it would display, in an indented vertical list, the subfolders on the left, and the graphical display on the right. Currently this program feels like it came from another OS to that of Nemo. Then again, i think it must be a Gnome thing, as  Disks (gnome-disk-utility 3.18.3.1) also has a weird title bar and an inconsistent look and feel to Nemo .

**Comment by JosephMcc** [comment]
The Mint team has nothing to do with baobab. It's design it what is provided from upstream. You will need to file issues for it against the upstream package.
