### ISSUE TITLE
Lack of translation

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxmint/mintmenu#176]
Lack of translation Transmission "Download and share files over BitTorrent" to pt_BR.

pt_BR Transferir e compartilhar arquivos através do BitTorrent

![captura de tela de 2017-05-19 13-21-27](https://cloud.githubusercontent.com/assets/8754997/26257488/307ad25c-3c97-11e7-924e-f803d1e93fa9.png)
![captura de tela de 2017-05-19 13-22-12](https://cloud.githubusercontent.com/assets/8754997/26257486/30764f34-3c97-11e7-9db5-0624e6ade753.png)

![captura de tela de 2017-05-19 13-29-02](https://cloud.githubusercontent.com/assets/8754997/26257535/6165a23e-3c97-11e7-9081-afc15fd856fb.png)

**Comment by JosephMcc** [comment]
Couple things. Mint menu has nothing to do with Cinnamon. It's the menu for Mate. If there is an issue with translations in Transmission you need to file a bug against them.

**Comment by GabrielMGitHub** [comment]
@JosephMcc This is lack of translation in the shortcut of nothing has to do with the application.

**Comment by GabrielMGitHub** [comment]
@JosephMcc Who makes the shortcut available is Linux Mint, not the application.
@clefebvre Look

**Comment by JosephMcc** [comment]
Sorry if I'm misunderstanding what the issue is here. Either way you are talking about Cinnamon which mintmenu has nothing to do with it.

**Comment by GabrielMGitHub** [comment]
@JosephMcc Look at the pictures, I said that translation is missing for description of the application for pt_BR language, as shown in the menu.

**Comment by GabrielMGitHub** [comment]
Open: https://github.com/linuxmint/Cinnamon/issues/6546
