### ISSUE TITLE
Remove os.system calls in the python plugins

### ISSUE THREAD

**Issue by TheRegRunner** [linuxmint/mintmenu#178]
Launchpad Bug No. 1586346

places.py 
recent.py
applications.py

Possible Shell injection
![bug screenshot](https://cloud.githubusercontent.com/assets/13422603/26485593/fe95213c-41f7-11e7-8910-263c8acdda26.png)

**Comment by xenopeek** [comment]
Thanks for contributing to mintmenu. As far as my testing confirmed, there was only one place where command substitution in they search keywords would cause this issue: in the apt search. Other places already quoted the search keywords before running a command and command substitution didn't happen there.
