### ISSUE TITLE
The transparency(0.8)  of mintmenu disappears but  it is ok at first time

### ISSUE THREAD

**Issue by tomsunchen** [linuxmint/mintmenu#181]
change opacity from 1 to 0.8 on show function of MainWindow, The transparency effect is  normal(0.8) when the mintmenu shows at first time, then it is abnormal when mintmenu shows again.

**Comment by marsjaninzmarsa** [comment]
Ke?

**Comment by xenopeek** [comment]
mintmenu had a transparency option in the past but it's no longer in current versions.
