### ISSUE TITLE
Super-Key blocked for other keyboard shortcuts on Mint 18.2

### ISSUE THREAD

**Issue by Zulgrib** [linuxmint/mintmenu#184]
Super key is consumed for some shortcuts :
Super > Open menu (ok)
Super D > Show desktop (ok)
Super E > Home (fail)
Super F > Search (fail)
Super L > Lock (fail)
#172 does not resolve the problem on it's own using default configuration provided by mint mate, excluding these custom shortcuts.

**Comment by monsta** [comment]
Should be fixed now with mate-settings-daemon update to 1.18.2.
