### ISSUE TITLE
Option to disable "Recently used Applications" in mintMenu

### ISSUE THREAD

**Issue by gusbrs** [linuxmint/mintmenu#186]
From https://forums.linuxmint.com/viewtopic.php?f=206&t=258697

I've recently updated my Linux Mint Mate to the most recent version 18.3 Sylvia and was, as usual, very much pleased with the improvements of the new version and with the overall system that I'm used to. (BTW, thank you very much for the great distro!)

There is, however one change that is bothering me. The "Recent documents" Menu plugin was updated to include "Recently used apps" as well. While I find it useful to have such feature for recent documents, which require sometimes several clicks to reach in the file manager, that is not the case for applications, which one keystroke (Super) and two or three letters suffice. Worse, by default the "Recently used applications" appears before "Recent documents" forcing one to dig through clicking here and there.

So, I kindly request the inclusion of an option to configure the Recent documents plugin / to disable Recently used applications (without disabling Recent documents plugin altogether).

**Comment by pas-calc** [comment]
this is saved in **dconf**  and can be reset using
`dconf reset /com/linuxmint/mintmenu/plugins/recent/recent-apps-list `
