### ISSUE TITLE
Moving to python 3

### ISSUE THREAD

**Issue by Fred-Barclay** [linuxmint/mintmenu#189]
Hi @clefebvre and everyone,
Apologies if this has already been asked and I missed it - I did find #161 but that looks like it's more concerned with GTK-3 than python 3.

Would contributions toward using python 3 for mintment be useful for you guys? I could start working on that if so.

Cheers!
Fred

**Comment by clefebvre** [comment]
Yes. Be careful with unicode... make sure to test in Russian and German (we find a lot of issues in these two languages when moving to Python3). PRs are welcome.
