### ISSUE TITLE
Feature request: clear search input entry after hiding the menu

### ISSUE THREAD

**Issue by rumly111** [linuxmint/mintmenu#192]
I open MintMenu and start typing "browser", it will show me my internet browsers and file browsers, which is fine. Then I chose a program or simply close the menu. Then I open the menu again, and in the search bar there is still "browser" word, but the menu items aren't filtered at all.

What I'd like is after the menu closes, the search bar clears it's contents.

**Comment by xenopeek** [comment]
You must have set the menu to remember your last search. You can disable that in the menu configuration. If you don't want to change the configuration: a change has already been implemented for the menu (https://github.com/linuxmint/mintmenu/pull/191) such that when you've set your menu to remember your last search, the next time you open your menu that search will be highlighted and you'll immediately overwrite it when you start typing (unless you first press left or right arrow key, then you can edit your previous search in place). This change should be in Linux Mint 19. As such, closing this issue.

**Comment by rumly111** [comment]
Thank you for explaining.
