### ISSUE TITLE
Upgrade to Mate 1.20.3

### ISSUE THREAD

**Issue by MartinX3** [linuxmint/mintmenu#194]
Dear Linux Mint Developers,

I have a question and don't know where to make the issue ticket.

When Linux Mint 19 will be shipped with Mate 1.20.3?
It is still 1.20.1.

1.20.3 contains useful bug fixes.

**Comment by clefebvre** [comment]
Hi,

MATE 1.20 is maintained by Ubuntu in Mint 19. We'll take over from them with the next release (1.22), but for now updates come from Ubuntu 18.04.

You can check the origin of a package with "apt policy", for instance: "apt policy caja".
