### ISSUE TITLE
Broke running with "xdg-su" in exec field

### ISSUE THREAD

**Issue by mrandybu** [linuxmint/mintmenu#199]
When .desktop contains "xdg-su" before command in exec field, program don't start. Need add two check. First, xdg-su on input get path with command only, if command has symbol %*, that running is failed. Second, if "xdg-su" in exec, that need add "-c" option, because, without "-c" , running failed.

**Comment by clefebvre** [comment]
Hi @mrandybu,

What's its Exec line?

Looking at https://github.com/openSUSE/imagewriter/blob/master/imagewriter.desktop#L4 it doesn't seem to contain xdg-su.

**Comment by clefebvre** [comment]
What's its Exec line?

**Comment by mrandybu** [comment]
Exec=/usr/bin/xdg-su -c /usr/bin/imagewriter %f

**Comment by mrandybu** [comment]
@clefebvre what do you think?

**Comment by clefebvre** [comment]
Thanks @mrandybu
