### ISSUE TITLE
Feature request: Allow execution of search string (in terminal)

### ISSUE THREAD

**Issue by Thomas12** [linuxmint/mintmenu#20]
When I enter some text in the mintmenu I get many suggestions of what to do with this entered string (e.g. lookup in dict). Could you please enhance the menu search option to have an entered string executed (in terminal) [only suggest (terminal-)execution if the command exists]? 

Example: I enter "top" + enter or maybe shift+enter to stress this is a command to be run in terminal. Then a terminal opens and top is run.

I enter "sdfsgd", terminal execution is not offered as this string does not belong to a program.

If possible, find a way to run GUI apps that are started with the method above without terminal. E.g. running the Calculator-Emulator tiemu, which has a gui but no mintmenu-shortcut when installed should start without a waiting black terminal in background as this is not a terminal-program - but I don't know how to distinguish that.

**Comment by xenopeek** [comment]
Thanks for contributing to mintmenu. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

Noting some default keyboard shortcuts for those interested:
- Alt+F2 opens the run application dialog, from which you can also issue commands to run on the terminal;
- Ctrl+Alt+T opens a terminal.
