### ISSUE TITLE
ImportError: No module named setproctitle

### ISSUE THREAD

**Issue by SpaceboyRoss01** [linuxmint/mintmenu#201]
I just installed `mintmenu` today and I got an error saying `ImportError: No module named setproctitle`

**Comment by clefebvre** [comment]
You need python-setproctitle

**Comment by SpaceboyRoss01** [comment]
I already have that installed.

**Comment by clefebvre** [comment]
Did you modify your python version or its import path?

What happens when you import the module from command line?
