### ISSUE TITLE
Menu extends off the top of the screen - fixed, perhaps?

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintmenu#202]
DE: Cinnamon
Frequency of problem: constant

In preparation for Mint 19.1, I replaced my dock with a bottom panel, and installed the Icing manager. My MintMenu ended up looking like this - where the top of the image is the top of my screen,

![image](https://user-images.githubusercontent.com/9998846/50052920-0f615c00-0124-11e9-8fef-7f19070c8259.png)

The menu's search box was not visible; when I started typing, trying to search within applications, the little Nemo desktop search box popped up.

I hope that this problem is fixed in the version of Cinnamon that comes with Mint 19.1 (I did test 19.1 in a VM, but I don't have so many applications installed in the VM, so I cannot test properly).

Cinnamon 3.8.9
HiDPI.
Intel integrated graphics.

Cf. [this existing (closed) bug report](https://github.com/linuxmint/Cinnamon/issues/6110), which says the problem is 'on the roadmap'. From [that roadmap](https://github.com/linuxmint/Roadmap), I was unable to tell (my mistake, perhaps) whether the problem had been fixed or not.

The problem _may_ have caused the following scenario (a scenario that occured shortly after I had setup the panel): the system alternated between being stuck in alt-tab mode and being in a situation were the 'coverflows' were not showing but winders were unclickable; ultimately I had to do a hard reboot.

**Comment by JosephMcc** [comment]
This is for Mint Menu that is used in Mint Mate. It is not a place for Cinnamon issues.
