### ISSUE TITLE
Why mintmenu reset environment variables?

### ISSUE THREAD

**Issue by x09** [linuxmint/mintmenu#209]
Chromium (MATE) doesn't run correctly without XDG_CONFIG_DIRS

**Comment by clefebvre** [comment]
I don't think it does... I can't find any reference to XDG_CONFIG_DIRS in mintmenu anyway. What's the Exec line for the app and what behaviour do you observe? (i.e. what goes wrong when running Chromium, so we can try and reproduce).

**Comment by x09** [comment]
i will try to explain.

1) make sure the variable is defined. 
run `echo $XDG_CONFIG_DIRS` - i get /etc/xdg

2) rename original chromium for test
`sudo mv /usr/bin/chromium /usr/bin/chromium.bak`

3) create test script
`sudo vim /usr/bin/chromium` wuth code

`#!/bin/bash
env >> /tmp/123.txt
`
sudo `chmod +x /usr/bin/chromium`

4) try run from terminal (not mintmenu!)
`/usr/bin/chromium`

5) look at the variables
`cat /tmp/123.txt | grep -i xdg`
output is
```
XDG_CONFIG_DIRS=/etc/xdg
XDG_RUNTIME_DIR=/run/user/500
```

all fine, but..

6) run Chromium from mintmenu and look at the variables
`cat /tmp/123.txt | grep -i xdg`
output is
`XDG_RUNTIME_DIR=/run/user/500`

XDG_CONFIG_DIRS is absent! why?

I go to source.
/usr/share/linuxmint/mintMenu/plugins/execute.py
```
...
    if desktopFile:
        launcher = Gio.DesktopAppInfo.new_from_filename(desktopFile)
        retval = launcher.launch_uris()
...
```

add set variable, one line

```
...
    if desktopFile:
	os.environ["XDG_CONFIG_DIRS"] = "/etc/xdg"
        launcher = Gio.DesktopAppInfo.new_from_filename(desktopFile)
        retval = launcher.launch_uris()
...
```

try run Chromium from mintmenu, then look at the variables
```
XDG_CONFIG_DIRS=/etc/xdg
XDG_RUNTIME_DIR=/run/user/500
```

all fine. But not a patch. Why system variables not inherited?

**Comment by gm10** [comment]
The menu runs in the panel's context. On LM19.1 MATE with the default mate-panel I got this in the environment: 
`XDG_CONFIG_DIRS=/etc/xdg/xdg-mate:/etc/xdg`
In other words, I can neither reproduce with the default setup nor could it be an issue with mintmenu in the first place.

**Comment by mikhailnov** [comment]
why is XDG_CONFIG_DIRS set and reset by panel?! `os.environ["XDG_CONFIG_DIRS"] = "/etc/xdg"`

**Comment by x09** [comment]
I run mintmenu on AltLinux, not LM.

**Comment by gm10** [comment]
Same answer.
