### ISSUE TITLE
missing custom icon prevents preferences from opening

### ISSUE THREAD

**Issue by cruftytheclown** [linuxmint/mintmenu#228]
If you are using a custom icon for the mintmenu, and then you delete that icon in caja, the menu preferences will no longer open.

syslog says the error is on line 340 of mintMenuConfig.py     (Failed to open file...)

Workaround is to reboot which somehow resets the preferences to the default icon.

**Comment by clefebvre** [comment]
This is with the PPA version right?

**Comment by cruftytheclown** [comment]
This is with stock Linux Mint 19.1 MATE 64-bit

**Comment by clefebvre** [comment]
This is fixed in 19.2, mintMenuConfig.py moved to preferences.py using an icon chooser.
