### ISSUE TITLE
Adding favorites to menu, the menu disappears.

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/mintmenu#232]
Mint 19.2 Cinnamon 64 bit.   NOT BETA.

When you right-click a program in the menu and chose 'add to favorites', the menu disappears (closes) immediately.  The program IS added but the menu should stay persistent so you can add more.   

This function has been reported to have worked in 19.1 and in MATE.   I personally did not test but asked others on the mozilla support newsgroup.

**Comment by clefebvre** [comment]
off topic, mintmenu is the MATE menu.

**Comment by ChooChooAl** [comment]
I'm a bit of a novice but the applet says menu@cinnamon.org  
How do you get MATE out of that?   I'm running Cinnamon!
