### ISSUE TITLE
Menu identifing and distinguishing duplicates does not work with Gnome Maps

### ISSUE THREAD

**Issue by kmkom** [linuxmint/mintmenu#234]
Linux Mint 19.2 Cinnamon

Installed Gnome maps 3.28  and because it didn't work (the location search does not jump to the location on the map!) additionally installed the Maps version from the Flatpak (3.32). According to the changes in Mint [Tina](https://www.linuxmint.com/rel_tina_cinnamon_whatsnew.php) two menu entries should appear now:

Maps
Maps (Flatpak)

But unfortunately there is only one entry "Maps" in the menu and this entry still starts the old version 3.28.

After uninstalling the buggy version 3.28, the entry Maps now calls the newer Flatpak version (and in this Version search does work).

**Comment by clefebvre** [comment]
Probably a refresh issue. However, this is off-topic here, mintmenu is the MATE menu.
