### ISSUE TITLE
Linux Mint Mate 19.2 upgrade lost Applications Menu

### ISSUE THREAD

**Issue by cemclellan** [linuxmint/mintmenu#235]
I have 2 ASUS laptops that were running Linux Mint Mate 19.1.

I upgraded my ASUS-Q302UA to Linux Mint 19.2 without any problems. After using it for a couple of days to verify the upgrade, I was happy with everything.

I then proceeded to upgrade my ASUS-Q524UQK. when I rebooted after the upgrade my applications menu was empty.

I rebooted again to see if it was a one-time problem, but once again the application menu has none of my installed applications.

If I use the Main Menu application from the Control Center, all of my applications show there. Also if I go to Favorites from the Applications Menu, my Favorites are still there.

If I type into the search box at the bottom of the Applications Menu, it does not find an application even though it is installed (verified from the terminal).

How do I get the Applications menu to work once more?

**Comment by Dehumanizer77** [comment]
I have the same problem, also running Mate, upgraded to 19.2 just now and all applications are gone from the menu. When I add Main Menu to the panel (not mintMenu), applications are there. Also when trying to edit the menu from the control center, it's not making any changes. Adding a folder or item does not do anything, items are not added.

**Comment by Dehumanizer77** [comment]
Another finding - I can delete items from the menu, but can't add new ones.

**Comment by gm10** [comment]
Because @Dehumanizer77 helped me out fixing the bug in my version of the menu: The bug is here https://github.com/linuxmint/mintmenu/blob/master/usr/lib/linuxmint/mintMenu/plugins/applications.py#L1626, `get_icon()` can return `None` now.

**Comment by ranokuhl** [comment]
I was able to resolve this one via Right mouse click on Panel > Troubleshoot > Restore all settings to default.
Just my 2 cents
![Screenshot from 2019-09-09 10-03-01](https://user-images.githubusercontent.com/46578162/64513900-d5f00280-d2e9-11e9-91a1-ee6f981533fe.png)

**Comment by Dmitry-NC** [comment]
Hi guys!
I have a similar problem, after updating September 16 from 9.1 to 9.2 there are no programs in the menu. It seems that no one is busy and does not dare.
![menu](https://user-images.githubusercontent.com/51990027/65120994-2c9ac200-d9f7-11e9-854d-e65d031df37f.png)
And I could not find a panel where you can at least fix something.
Does anyone even do this?

**Comment by warepilot** [comment]
### Error ###
Application list is empty on Mint menu but favorites still remain.

### Steps to reproduce ###
Drag and drop one whole category inside another category.
This will make close the menu editor window and make useless menu edition action.

### Solution 1 ###
Restore the following files according to your distribution...
```
~/.config/menus/mate-applications.menu
~/.config/menus/mate-settings.menu
```
They can be copied from another user in the system. These files contain the place and categories where application lists are loaded from. Apparently favorites are not affected.

### Solution 2 ###
Open `~/.config/menus/mate-applications.menu` in a text editor. You'll see it's kind of a XML file. Find a place where there is a category inside another and another and another... I would consider this a bug... Clear the parent category that's creating this bizarre tree. Save it and try edit menu again. At least for me the menu editor shows again and applications are loaded again without restarting session.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintmenu/commit/3d3876573405509bbeace91c171c8ac28a71dafa
