### ISSUE TITLE
Incompatibility between mintmenu and antiword

### ISSUE THREAD

**Issue by paeleog** [linuxmint/mintmenu#239]
On downloading antiword 0.37-11build1 mintmenu 5.9.8 consistently loses all the applications in the right hand panel. Removing antiword and the applications consistently reappear.
I am using Linuxmint 19.2 Mate 1.22.0 on Dell Inspiron-15-3567, Kernel 4.15.0-64-genericx86_64 and Intel® Core™ i3-7020U CPU @ 2.30GHz × 4

**Comment by clefebvre** [comment]
Thanks @paeleog I can reproduce it.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintmenu/commit/3d3876573405509bbeace91c171c8ac28a71dafa

**Comment by paeleog** [comment]
Excellent. Thank you clefebvre.
