### ISSUE TITLE
mint 19.2 mate, mintmenu problem

### ISSUE THREAD

**Issue by 2jcm** [linuxmint/mintmenu#241]
I tried to add Palemoon to the Internet using 'Edit Menus'.  When it got to search for a working directory, the Palemoon launcher is grayed out so you can't add PM to the Internet.
I used a right click 'Add to Panel' for a custom application launcher, and it worked perfectly.
the PM launcher was NOT grayed out so, at least i have a launcher on my panel.

**Comment by xenopeek** [comment]
Good workaround. I can't reproduce the issue but the palemoon package from their website currently (perhaps not previously) does already add an entry in the Internet category of your menu. Use the package for xUbuntu 18.04 from their website for Linux Mint 19.x.
