### ISSUE TITLE
mintMenu doesn't run multiple commands

### ISSUE THREAD

**Issue by bartszu** [linuxmint/mintmenu#243]
Well I guess Lefebvre`s  "Need to Update" principle just went to bin.
Sorry by 19.3 is a mayor step backward, really big one.
I never thought it will come to this stage, of switching distro.
This update of Advanced Mint Mate Menu ( AMMM ) is pure, totally unnecessary disaster,

Condition to reproduce:
Freshly installed Linux Mint 19.3 Tricia 32-bit Mate

Error or New Feature:

Advanced Mint Mate Menu is ignoring updates of commands done from Edit Properties:
![Menu_007](https://user-images.githubusercontent.com/8744067/76723132-2daa7300-673e-11ea-8025-7739bb0f28f8.jpg)

This wont work and is completely ignored by AMMM.
Despite this will run all fine from Terminal.
![Selection_004](https://user-images.githubusercontent.com/8744067/76723213-6cd8c400-673e-11ea-9a0a-88368eb3fc64.jpg)

**Comment by bartszu** [comment]
Guys really please have some mercy.
And at least add to apt 5.9.0.
This 6.0.3 it is one big trash, done purely for purpose of having nice GTK3 dialog boxes.
They are improvements to be made to it, do plugin to put Search Box up like in Soulus Mate.
Just stop massacre it.

Sorry I must change it to this.
https://mint.pkgs.org/19.1/mint-main-i386/mintmenu_5.9.1_all.deb.html

**Comment by bartszu** [comment]
OMG what kind of release is this !!!!
![Selection_012](https://user-images.githubusercontent.com/8744067/76728169-e0ce9880-674d-11ea-9200-1b4ff34871d4.jpg)

**Comment by xenopeek** [comment]
I don't know that this has changed but the menu command launcher isn't a shell interpreter so it doesn't handle shell operators such as &&.

To have the menu run multiple commands, you can invoke a shell interpreter to run your commands. For your example for your command by calling it with `bash -c` like this:
```
bash -c 'xdotool set_desktop 6 && gnome-calculator'
```
After editing Calculator's menu entry that works for me. I tested with command `bash -c 'zenity --question && gnome-calculator'` to give me clear feedback it's working.

**Comment by bartszu** [comment]
In 19.2 all those commands work no problem in a form.
`xdotool set_desktop 6 && gnome-calculator
`
Anyway yes sorry this works as expected, Thanks Xeno ;)
`bash -c 'xdotool set_desktop 6 && gnome-calculator'
`
