### ISSUE TITLE
No response from AMM context menu.

### ISSUE THREAD

**Issue by bartszu** [linuxmint/mintmenu#252]
Well I am pretty sure issue is reproductable.
I have this issue on second Mint installation.

Recently was forced to install Mint 19,3 32bit, due to hardware constrains, 32bit proc.

So I can reproduce this on 32bit and 64bit builds.

Other circumstances: 

1. 
Well I always use deconf-editor.
To lock and unlock panels.

This seems to be irrelevant to me, as I even restarted with lock feature on and off.
No change to problem.

2. 
I don`t  remember this happening in 19,2.
So we are talking about system updated to 19.3 with

sudo apt update && sudo apt upgrade

******************************

Ok issue goes like that:
So right click on AMM buttom brings contex menu.
![Menu_228](https://user-images.githubusercontent.com/8744067/82808015-f44e5c00-9e80-11ea-8bba-8b8a5e9c45a5.jpg)
Here unlocked.

Left click on preferences should run preferences dialog box.
But nothing happens ;(

******************************************************

Well this is just educated guess, as my Python is basic.
But I looked at mintMenu.py imports.
And I think issue my be in using ubuntu2.3 version, instead of simply ubuntu2.

![Selection_226](https://user-images.githubusercontent.com/8744067/82808204-6cb51d00-9e81-11ea-9d37-c8bb0e4cf6d8.jpg)

********************************************************

But downgrading this package actually warns me, I want to uninstall tons of Mate dependencies.

Like I said. This is guess, but I would go with.

sudo apt purge xdg-utils=1.1.2-1ubuntu2.3
sudo apt install xdg-utils=1.1.2-1ubuntu2

Althou I won`t press enter on that.

**Comment by mtwebster** [comment]
What happens if you run `/usr/lib/linuxmint/mintMenu/preferences.py` from a terminal?

**Comment by bartszu** [comment]
![Selection_229](https://user-images.githubusercontent.com/8744067/82857317-8d748580-9f08-11ea-8bce-9bcb8babdd28.jpg)

**Comment by bartszu** [comment]
C++ error, so this comes from dependencies.
I am pretty sure issue was non-existent in 19.2,
So issue occurs only in new update of preferences.py

**Comment by clefebvre** [comment]
preferences.py works here, with xdg-utils=1.1.2-1ubuntu2.3 and mintmenu=6.0.3.1

**Comment by mtwebster** [comment]
Ok, first, let's try a simple potential fix, reinstall mintmenu:
```sudo apt-get reinstall mintmenu```

If that doesn't work, can you do the following:

- Enable debug repositories in Software Sources (mintsources)
- Install `libgtk-3-0-dbgsym`, `libglib2.0-0-dbgsym` and `gdb`
- `gdb python3`
- execute `run /usr/lib/linuxmint/mintMenu/preferences.py`
- When the segfault occurs, `thread apply all bt`

**Comment by bartszu** [comment]
> preferences.py works here, with xdg-utils=1.1.2-1ubuntu2.3 and mintmenu=6.0.3.1

Hmm strange, here not on 2 PCs.
Let me apply MtWebster proposal.

**Comment by bartszu** [comment]
![Selection_233](https://user-images.githubusercontent.com/8744067/82907541-a7d94e00-9f5e-11ea-9687-2537ed666c0a.jpg)

**Comment by mtwebster** [comment]
run ```thread apply all bt``` at that prompt

**Comment by bartszu** [comment]
Hmm I don`t know.
I would not bother writing, if I did not have it now on 2 machines, here.
But I guess it must be something I have locally only here.

This bugs me:
1894	../../../../glib/ghash.c: No such file or directory.

Anyway never mind I guess I will just reinstall.
ty
