### ISSUE TITLE
Appimage at mintmenu

### ISSUE THREAD

**Issue by svastian99** [linuxmint/mintmenu#253]
Is there any chance to pin an Appimage app as a mintmenu {or default software} item?

**Comment by xenopeek** [comment]
mintMenu displays menu launchers registered at the system or user level. Some AppImages add a menu launcher but many don't. You can use [AppImageLauncher](https://www.appimagehub.com/p/1228228) to better integrate such AppImages. See the video on the linked page for explanation.

**Comment by svastian99** [comment]
Thank you very much, now I understand that it does not depend on mint. Cheers

P.S. I wish in the future there was a way to set Appimage as default apps
