### ISSUE TITLE
ImageMagick is strange in Linux Mint MATE 20 menu

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mintmenu#254]
New fresh install (no upgrade from older version) :

![Capture du 2020-07-10 22-11-15](https://user-images.githubusercontent.com/3955499/87197351-a390a680-c2fa-11ea-8f57-c4541c767aa3.png)

**Comment by xenopeek** [comment]
That's what is in the Name field of its .desktop file (package imagemagick-6.q16 from Focal repository).

This is an observation not a bug. Please don't report observations here. See our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) for making good bug reports. If you need help with troubleshooting an observation you can take help from the [support forums](https://forums.linuxmint.com/).

**Comment by InfoLibre** [comment]
The problem with Linux Mint is that it is based on Ubuntu, that is based on Debian and that finding the good place where to report becomes extraordinary complicated for a normal user. When you make a report because something is wrong (and having **(color depth=16)** in a menu is wrong, even it's it is a small bug, I will never find this in Windows), the answer is always that it is not a bug or go and see Ubuntu or Debian, MATE, Cinnamon, other softwares...
It's not really quality oriented. The result is that more and more users will stop to contribute and that you wil have more and more small bugs like that in Linux Mint after each version. I can see sometimes messages in Linux Mint forums and blog that complain about that and you should change it. Perhaps with not closing reports but closing them **after** moving them to Ubuntu/Debian/MATE/Cinnamon but with asking money for this service. A sort of bug bounty.

**Comment by InfoLibre** [comment]
I could indeed modify my .desktop file but in the next release of Linux Mint, the menu will contain again **(color depth=16)**. That's why I say it's a bug.

**Comment by leigh123linux** [comment]
> I could indeed modify my .desktop file but in the next release of Linux Mint, the menu will contain again **(color depth=16)**. That's why I say it's a bug.
> 
> Who will read the 15 pages of https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/ ?
> Which category user must choose ??? https://github.com/linuxmint
> Users are lost :
> https://forums.linuxmint.com/viewtopic.php?t=272523
> https://community.linuxmint.com/idea/view/2097
> 
> face_with_head_bandage

Go and bug someone else

https://bugs.launchpad.net/ubuntu/+source/imagemagick/

**Comment by InfoLibre** [comment]
Thank you for the link. I made a new report : https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1887275
