### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by Isakku** [linuxmint/mintmenu#262]
OK there are some little features  (but very very very important for me) that we used to have in previous Mate versions and that are missing in Mint Mate 20.1.

This is what my current Mint Mate desktop looks like in my machine
![PanelAndMenuLooksOptions](https://user-images.githubusercontent.com/16464336/103433956-47834c80-4bd0-11eb-9864-0c6ea70138f1.png)

And this is what it looks like when I try to make the same configurations in Mint Mate 20.1

![Mate 20 1 Desktop missing feature Screenshot at 2021-01-01 04-58-32](https://user-images.githubusercontent.com/16464336/103433969-7699be00-4bd0-11eb-90e9-cab4506d4deb.png)

It's completely missing all the customization options in the "appeareance" tab!
NO custom background color!
NO custom text color! 
NO custom opacity for background color!

Please don't forget to add all those back! 
Quality should be kept and maintained! 
Having optional things like those are the reason I like the Mate desktop!
(At least the panel does have those options or so it seemed to me and I am grateful you guys didn't forget those options there
I think it shouldn’t be too hard to recover those missing features, as they are already present in the current panel incarnation but missing in the mint menu.)

**Comment by clefebvre** [comment]
@Isakku we lost these when moving to GTK3. It's been a while now. They were quite buggy and hard to port so they were removed.
