### ISSUE TITLE
Plugin "Applications" not loading on new user

### ISSUE THREAD

**Issue by TailsFanLOL** [linuxmint/mintmenu#271]
Plugin "Applications" not loading on new user (see screenshots at the bottom). Works fine on main user.
Sorry for making this report very long.

I:

1. created a new user;
2. set name, home phone number (if that matters somehow), rights;
3. login.
Sysinfo:

> ```
> 
> System:    Kernel: 5.4.0-105-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 Desktop: MATE 1.26.0 
>            wm: marco dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
> Machine:   Type: Portable System: Dell product: Inspiron 5748 v: N/A serial: <filter> Chassis: 
>            type: 8 serial: <filter> 
>            Mobo: Dell model: 0JF5N2 v: A12 serial: <filter> UEFI: Dell v: A12 date: 05/13/2016 
> Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard serial: <filter> 
>            charge: 55% (should be ignored) status: Discharging 
> CPU:       Topology: Dual Core model: Intel Core i3-4030U bits: 64 type: MT MCP arch: Haswell 
>            rev: 1 L2 cache: 3072 KiB 
>            flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 15163 
>            Speed: 1895 MHz min/max: 800/1900 MHz Core speeds (MHz): 1: 1895 2: 1895 3: 1896 
>            4: 1895 
> Graphics:  Device-1: Intel Haswell-ULT Integrated Graphics vendor: Dell driver: i915 v: kernel 
>            bus ID: 00:02.0 chip ID: 8086:0a16 
>            Device-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] 
>            vendor: Dell driver: nvidia v: 340.108 bus ID: 08:00.0 chip ID: 10de:1140 
>            Display: x11 server: X.Org 1.20.13 driver: modesetting,nvidia 
>            unloaded: fbdev,nouveau,vesa compositor: marco resolution: 1600x900~60Hz 
>            OpenGL: renderer: GeForce 820M/PCIe/SSE2 v: 4.4.0 NVIDIA 340.108 direct render: Yes 
> Audio:     Device-1: Intel Haswell-ULT HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
>            bus ID: 00:03.0 chip ID: 8086:0a0c 
>            Device-2: Intel 8 Series HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
>            bus ID: 00:1b.0 chip ID: 8086:9c20 
>            Device-3: Tenx type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-1.3:4 
>            chip ID: 1130:1620 
>            Sound Server: ALSA v: k5.4.0-105-generic 
> Network:   Device-1: Broadcom and subsidiaries BCM43142 802.11b/g/n 
>            vendor: Dell Wireless 1704 802.11n + BT 4.0 driver: wl v: kernel port: f040 
>            bus ID: 06:00.0 chip ID: 14e4:4365 
>            IF: wlp6s0 state: up mac: <filter> 
>            Device-2: Realtek RTL810xE PCI Express Fast Ethernet vendor: Dell driver: r8169 
>            v: kernel port: e000 bus ID: 07:00.0 chip ID: 10ec:8136 
>            IF: enp7s0 state: down mac: <filter> 
> Drives:    Local Storage: total: 465.76 GiB used: 102.54 GiB (22.0%) 
>            ID-1: /dev/sda vendor: Western Digital model: WDBNCE5000PNC size: 465.76 GiB 
>            speed: 6.0 Gb/s serial: <filter> 
> Partition: ID-1: / size: 456.83 GiB used: 102.51 GiB (22.4%) fs: ext4 dev: /dev/sda4 
>            ID-2: swap-1 size: 256.0 MiB used: 28.0 MiB (10.9%) fs: swap dev: /dev/sda3 
> USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
>            Hub: 1-1:2 info: Intel ports: 8 rev: 2.0 chip ID: 8087:8000 
>            Device-1: 1-1.1:3 info: Logitech Unifying Receiver type: Keyboard,Mouse 
>            driver: logitech-djreceiver,usbhid rev: 2.0 chip ID: 046d:c534 
>            Device-2: 1-1.3:4 info: Tenx type: Audio,HID driver: hid-generic,snd-usb-audio,usbhid 
>            rev: 1.1 chip ID: 1130:1620 
>            Device-3: 1-1.6:5 info: Broadcom BCM43142 Bluetooth 4.0 type: <vendor specific> 
>            driver: btusb rev: 2.0 chip ID: 0a5c:21d7 
>            Device-4: 1-1.8:6 info: Realtek RTS5129 Card Reader Controller type: <vendor specific> 
>            driver: rtsx_usb,rtsx_usb_ms,rtsx_usb_sdmmc rev: 2.0 chip ID: 0bda:0129 
> Sensors:   System Temperatures: cpu: 53.0 C mobo: 50.0 C gpu: nvidia temp: 44 C 
>            Fan Speeds (RPM): cpu: 2389 
> Repos:     No active apt repos in: /etc/apt/sources.list 
>            Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
>            1: deb https: //dl.winehq.org/wine-builds/ubuntu/ focal main
>            Active apt repos in: /etc/apt/sources.list.d/graphics-drivers-ppa-focal.list 
>            1: deb http: //ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal main
>            2: deb-src http: //ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal main
>            Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
>            1: deb https: //linuxmint.astra.in.ua/packages una main upstream import backport
>            2: deb http: //ubuntu.mirrors.omnilance.com/ubuntu focal main restricted universe multiverse
>            3: deb http: //ubuntu.mirrors.omnilance.com/ubuntu focal-updates main restricted universe multiverse
>            4: deb http: //ubuntu.mirrors.omnilance.com/ubuntu focal-backports main restricted universe multiverse
>            5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
>            6: deb http: //archive.canonical.com/ubuntu/ focal partner
>            Active apt repos in: /etc/apt/sources.list.d/official-source-repositories.list 
>            1: deb-src https: //linuxmint.astra.in.ua/packages una main upstream import backport
>            2: deb-src http: //ubuntu.mirrors.omnilance.com/ubuntu focal main restricted universe multiverse
>            3: deb-src http: //ubuntu.mirrors.omnilance.com/ubuntu focal-updates main restricted universe multiverse
>            4: deb-src http: //ubuntu.mirrors.omnilance.com/ubuntu focal-backports main restricted universe multiverse
>            5: deb-src http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
>            6: deb-src http: //archive.canonical.com/ubuntu/ focal partner
>            Active apt repos in: /etc/apt/sources.list.d/steam.list 
>            1: deb [arch=amd64,i386] https: //repo.steampowered.com/steam/ stable steam
>            2: deb-src [arch=amd64,i386] https: //repo.steampowered.com/steam/ stable steam
>            Active apt repos in: /etc/apt/sources.list.d/vscode.list 
>            1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
> Info:      Processes: 242 Uptime: 1h 53m Memory: 3.75 GiB used: 2.63 GiB (70.3%) Init: systemd 
>            v: 245 runlevel: 5 Compilers: gcc: 9.4.0 alt: 8/9 Client: Unknown python3.8 client 
>            inxi: 3.0.38 
> 
> 
> 
> ```
Screenshots:
![Снимок экрана в 2022-03-27 20-51-03](https://user-images.githubusercontent.com/96183936/160298106-62b8953a-c5ff-4256-919f-e00b4c39ec08.png)
![изображение](https://user-images.githubusercontent.com/96183936/160298612-b5d0c129-a3fa-4f1b-8ee5-87dd8ba5d2e4.png)
![изображение](https://user-images.githubusercontent.com/96183936/160298619-fd1ecb28-37a5-4405-877b-4449afe5e818.png)
![изображение](https://user-images.githubusercontent.com/96183936/160298643-1416e3e2-3208-441a-a381-d9e98d21ad2f.png)

**Comment by Kuzm1ch-dev** [comment]
Exactly the same problem, when creating a new user, the menu does not work for him

**Comment by TailsFanLOL** [comment]
Nvm I just had to reinstall the `mint-menu` package and it just worked
