### ISSUE TITLE
Feature Request: mintmenu search should function similarly to, but slightly better than, cinnamon menu (auto-complete.)

### ISSUE THREAD

**Issue by 0xnate** [linuxmint/mintmenu#41]
This revolves mostly around the 'hit meta/windows key, type something, hit enter' work-flow. For instance, assuming firefox is installed, hitting the meta/windows key(or alt-f1 in kde) in cinnamon or windows 7, typing 'firef', then hitting enter, will launch firefox. Given that 'firefox' is both the friendly and actual command name, this isn't that impressive. As another example, take 'terminal'. If you type 'term' and hit enter in the cinnamon menu, it will launch the terminal even though the command is 'gnome-terminal' (and terminal is the friendly name/description.) In cinnamon, this auto-complete applies only to items in the menu. If you type 'ljh;jdfh;dafjhsd;f' and that matches no program command or description and hit enter, nothing happens. 

In the current mintmenu setup, if you type a partial command name or partial friendly name (like 'firef' or 'term') and hit enter, it launches a file search.

My request is that the default behavior of mintmenu function similarly to cinnamon menu, but slightly smarter. By default, mintmenu should auto-complete commands and descriptions/friendly names (like cinnamon does), but if nothing is found in the menu (for instance, when typing 'twrm' and hitting enter), it should default to a file search (which is the current default behavior unless you type a full command.)

**Comment by ewan86** [comment]
Plus one for this, would be the biggest improvement to mint mate they could make for me!

**Comment by xenopeek** [comment]
This seems to work as suggested when testing on Linux Mint 18.3 MATE. I tried:

- Hit Super
- Type "firef"
- Hit Enter and Firefox is launched
- Hit Super
- Type "term"
- Hit Enter and GNOME Terminal is launched
