### ISSUE TITLE
I can not bind any hotkey having "slash" in it.

### ISSUE THREAD

**Issue by LavirtheWhiolet** [linuxmint/mintmenu#42]
For example, when I set "<Primary><Alt>slash" as a hotkey and click "Close", the menu hangs up. And after reboot it does not react on this hotkey (while it is still "<Primary><Alt>slash" in its settings).

**Comment by xenopeek** [comment]
This appears to have been an issue with incorrectly configured keyboard layout, as binding slash demonstrable worked fine with correctly configured keyboard layout. Closing.
