### ISSUE TITLE
Custom color options on Theme tab

### ISSUE THREAD

**Issue by arehtykitna** [linuxmint/mintmenu#87]
Please add the option to change text color.

Example, you are using a light blue GTK theme (Blue-Submarine) with black dialogue text and want mintmenu to have a black background to match the MATE panel.

If you do this at present, all menu text cannot be seen. An extra text colour option to change it to any other colour would fix this.

**Comment by marsjaninzmarsa** [comment]
@MichaelTunnell any progress? PR maybe?

**Comment by clefebvre** [comment]
Hi, there, a PR for this is welcome.

**Comment by MichaelTunnell** [comment]
Unfortunately my solution is theme based via gtkrc and not via the menu. I have not had time to learn how the options are made in order to offer the control to the user but when I do I will submit a PR though based on when I first commented here, who knows when that will be. :)

**Comment by lburgazzoli** [comment]
@MichaelTunnell any chance to share your gtkrc ?

**Comment by MichaelTunnell** [comment]
Unfortunately, @lburgazzoli I don't have this anymore. I stopped using MATE a while back and I don't know if I saved this anywhere or not. I will take a look for it and if I don't find it I will recreate it but not sure when that will happen.

**Comment by arehtykitna** [comment]
Hi, I'm closing this issue because as of MATE 1.16 GTK+3 the switch to mate-menu resolves this issue. using blue-submarine mate-menu now has the dark background with white text and blue highlight I was aiming for in the first place.
