### ISSUE TITLE
adobe reader not accessible after search and down key

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintmenu#95]
if i open the menu and type 'adobe', adobe reader 9 will appear, but i cant access it with pressing the down key as i normally do for other searches.

**Comment by xenopeek** [comment]
This appears to have been fixed at some point. After installing djview4 and hardinfo, searching for them in the menu works as expected and down arrow key can be used to select them if they weren't already highlighted as the first match. Closing.
