### ISSUE TITLE
Black background in Mate Desktop 1.9.2

### ISSUE THREAD

**Issue by tagatac** [linuxmint/mintmenu#99]
![blackmintmenu](https://cloud.githubusercontent.com/assets/1304425/3636144/bb330a1e-0fa3-11e4-940c-856c80c56f95.png)
mintmenu 5.5.8
mate-desktop/mate-desktop@cd8fb2959520b12480291b3d14c78b7167bcd664

**Comment by marsjaninzmarsa** [comment]
@MichaelTunnell, this is not duplicate of #87, because #87 affects situation when you have dark theme loaded. In this case we can see that no theme is loaded. :P
